# Generated by Django 5.2 on 2025-04-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="typ",
            field=models.CharField(default="action", max_length=10),
        ),
    ]
